"use client";
import{useEffect,useMemo,useState}from"react";import{Bell,Search,RefreshCw,ExternalLink,TrendingUp,Newspaper,Radio,Sparkles,Bookmark,BarChart3,Globe2,Zap,CheckCircle2}from"lucide-react";
type A={id:string;title:string;summary:string;source:string;articleUrl:string;category:string;publishedAt:string;language?:string;clusterId?:string|null};type T={title:string;category:string;language?:string;sources:string[];count:number;sourceCount:number;newestAt:string;stories:A[]};
const cats=["All","Politics","Business","Sports","Technology","Crime","Health","Education","Weather","Entertainment","Science","World"];const langs=[["all","All"],["en","English"],["si","සිංහල"],["ta","தமிழ்"]];
export default function Home(){const[a,setA]=useState<A[]>([]),[s,setS]=useState<any>({}),[cat,setCat]=useState("All"),[lang,setLang]=useState("all"),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[brief,setBrief]=useState<any[]>([]),[trend,setTrend]=useState<T[]>([]),[sources,setSources]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>({}),[summaries,setSummaries]=useState<Record<string,string>>({}),[saved,setSaved]=useState<string[]>([]),[follow,setFollow]=useState<string[]>([]);
useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem("ln_saved")||"[]"));setFollow(JSON.parse(localStorage.getItem("ln_follow")||"[]"))}catch{}load();if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});const timer=setInterval(checkAlerts,120000);return()=>clearInterval(timer)},[])
async function checkAlerts(){try{const j=await fetch("/api/alerts",{cache:"no-store"}).then(r=>r.json());const seen=JSON.parse(localStorage.getItem("ln_alerts")||"[]");const fresh=(j.alerts||[]).filter((x:any)=>!seen.includes(x.id));if(fresh.length&&"Notification"in window&&Notification.permission==="granted")fresh.slice(0,3).forEach((x:any)=>new Notification("LankaNews: "+x.category,{body:x.title}));localStorage.setItem("ln_alerts",JSON.stringify((seen.concat(fresh.map((x:any)=>x.id))).slice(-100)))}catch{}}
function enableAlerts(){if("Notification"in window)Notification.requestPermission()};
async function load(){const[j,b,t,so,an]=await Promise.all([fetch("/api/articles",{cache:"no-store"}),fetch("/api/brief",{cache:"no-store"}),fetch("/api/trending",{cache:"no-store"}),fetch("/api/sources",{cache:"no-store"}),fetch("/api/analytics",{cache:"no-store"})]);const x=await j.json();setA(x.articles);setS(x.stats);setBrief((await b.json()).sections||[]);setTrend((await t.json()).items||[]);setSources((await so.json()).sources||[]);setAnalytics(await an.json())}
async function refresh(){setBusy(true);try{await fetch("/api/ingest",{method:"POST"});await load()}finally{setBusy(false)}}
async function summarize(id:string){const j=await(await fetch("/api/summarize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id})})).json();if(j.summary)setSummaries(x=>({...x,[id]:j.summary}))}
function toggleSave(id:string){const n=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(n);localStorage.setItem("ln_saved",JSON.stringify(n))}
function toggleFollow(c:string){const n=follow.includes(c)?follow.filter(x=>x!==c):[...follow,c];setFollow(n);localStorage.setItem("ln_follow",JSON.stringify(n))}
const f=useMemo(()=>a.filter(x=>(cat==="All"||x.category===cat)&&(lang==="all"||x.language===lang)&&(!follow.length||follow.includes(x.category))&&(!q||x.title.toLowerCase().includes(q.toLowerCase())||x.summary.toLowerCase().includes(q.toLowerCase()))),[a,cat,lang,q,follow]);
const breaking=a.filter(x=>Date.now()-+new Date(x.publishedAt)<3600000).slice(0,6),savedArticles=a.filter(x=>saved.includes(x.id));
return <main><nav><div className="brand">🇱🇰 <b>LankaNews</b> <i>AI</i></div><div className="links"><a href="#trending">Trending</a><a href="#latest">Latest</a><a href="#brief">Brief</a><a href="#analytics">Analytics</a><a href="/timeline">Timeline</a><a href="/entities">Entities</a><a href="/ask">Ask AI</a><a href="/digest">Brief</a><a href="/map">Map</a><a href="/trends">Trends</a><a href="/compare">Compare</a><a href="/archive">Archive</a><a href="/events">Events</a><a href="/districts">Districts</a><a href="/sports">Sports</a><a href="/business">Business</a><a href="/emergency">Emergency</a><a href="/widgets">API</a></div><button className="icon" onClick={enableAlerts} title="Enable breaking alerts"><Bell size={17}/></button></nav>
<section className="hero"><div><label>● LIVE SRI LANKA NEWS INTELLIGENCE</label><h1>Know what’s happening.<br/><span>Not just what was published.</span></h1><p>One intelligent feed from Sri Lankan publishers, with multilingual discovery, story clustering, source comparison and daily intelligence.</p><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search stories, topics or keywords..."/></div></div><aside><small>LIVE MONITOR</small><strong>{s.total||0}</strong><span>stories in the feed</span><button onClick={refresh} disabled={busy}><RefreshCw size={15}/> {busy?"Collecting…":"Collect latest"}</button></aside></section>
<section className="stats"><div><Newspaper/><b>{s.total||0}</b><small>Stories tracked</small></div><div><Radio/><b>{s.sources||0}</b><small>Publishers</small></div><div><TrendingUp/><b>{s.recent||0}</b><small>Last hour</small></div><div><Globe2/><b>{(s.languages?.si||0)+(s.languages?.ta||0)+(s.languages?.en||0)}</b><small>Language-detected</small></div></section>
<section className="featureStrip"><div><Zap/><b>{breaking.length} breaking-window stories</b><span>Published in the last hour</span></div><div><Bookmark/><b>{savedArticles.length} saved</b><span>Your local reading list</span></div><div><CheckCircle2/><b>{sources.filter(x=>x.status==="active").length}/{sources.length} sources active</b><span>Feed health</span></div></section>
<section className="panel" id="trending"><div className="head"><div><label>TRENDING NOW</label><h2>Stories across publishers</h2></div></div><div className="trendGrid">{trend.slice(0,6).map((x,i)=><div className="trendCard" key={x.title}><span>#{i+1}</span><b>{x.title}</b><small>{x.sourceCount} publishers · {x.count} matching stories · {x.category}</small><div>{x.sources.map(z=><em key={z}>{z}</em>)}</div></div>)}</div></section>
<section className="content" id="latest"><div className="head"><div><label>DISCOVER</label><h2>Latest intelligence</h2></div></div><div className="chips">{cats.map(c=><button className={cat===c?"active":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="langchips">{langs.map(([v,l])=><button className={lang===v?"active":""} onClick={()=>setLang(v)} key={v}>{l}</button>)}</div><div className="followRow"><span>Personal feed:</span>{cats.slice(1).map(c=><button className={follow.includes(c)?"follow on":"follow"} onClick={()=>toggleFollow(c)} key={c}>{follow.includes(c)?"✓ ":""}{c}</button>)}</div><div className="grid">{f.map(x=><article className="card" key={x.id}><div className="meta"><b>{x.category}</b><span>{x.source}</span><span>{x.language==="si"?"සිංහල":x.language==="ta"?"தமிழ்":"EN"}</span></div><h3>{x.title}</h3><p>{summaries[x.id]||x.summary}</p><div className="actions"><button onClick={()=>summarize(x.id)}><Sparkles size={13}/> AI summary</button><button onClick={()=>toggleSave(x.id)} className={saved.includes(x.id)?"saved":""}><Bookmark size={13}/> {saved.includes(x.id)?"Saved":"Save"}</button></div><footer><span>{new Date(x.publishedAt).toLocaleString("en-LK")}</span><a href={x.articleUrl} target="_blank" rel="noreferrer">Original <ExternalLink size={13}/></a></footer></article>)}</div></section>
{savedArticles.length>0&&<section className="panel"><div className="head"><div><label>READING LIST</label><h2>Saved stories</h2></div></div><div className="savedList">{savedArticles.slice(0,8).map(x=><a href={x.articleUrl} target="_blank" rel="noreferrer" key={x.id}><b>{x.title}</b><span>{x.source} · {x.category}</span></a>)}</div></section>}
<section className="brief" id="brief"><div><label>LAST 24 HOURS</label><h2>Daily Brief</h2><p>{brief.reduce((n,x)=>n+x.count,0)} stories grouped across {brief.length} active categories.</p></div><div className="road">{brief.slice(0,6).map(x=><div key={x.category}><b>{x.category}</b><span>{x.count} stories · {x.stories[0]?.title||"No headline available"}</span></div>)}</div></section>
<section className="panel" id="analytics"><div className="head"><div><label>SYSTEM ANALYTICS</label><h2>News pulse</h2></div></div><div className="analyticsGrid"><div className="chart"><h3>Last 7 days</h3>{(analytics.daily||[]).map((d:any)=><div className="barRow" key={d.date}><span>{d.date.slice(5)}</span><div><i style={{width:Math.min(100,(d.count/Math.max(1,...(analytics.daily||[]).map((z:any)=>z.count)))*100)+"%"}}/></div><b>{d.count}</b></div>)}</div><div className="chart"><h3>Top categories</h3>{(analytics.byCategory||[]).slice(0,7).map((d:any)=><div className="simpleRow" key={d.category}><span>{d.category}</span><b>{d.count}</b></div>)}</div><div className="chart"><h3>Publisher coverage</h3>{(analytics.bySource||[]).map((d:any)=><div className="simpleRow" key={d.source}><span>{d.source}</span><b>{d.count}</b></div>)}</div></div></section>
<section className="panel"><div className="head"><div><label>SOURCE MONITOR</label><h2>Publisher health</h2></div></div><div className="sourceGrid">{sources.map(x=><div className="sourceCard" key={x.name}><span className={x.status==="active"?"dot ok":"dot"}></span><b>{x.name}</b><small>{x.articles} stored stories</small><a href={x.url} target="_blank" rel="noreferrer">Publisher <ExternalLink size={12}/></a></div>)}</div></section>
<footer><b>LankaNews AI</b><span>Original publishers remain the source of record. AI summaries are clearly labeled.</span></footer></main>}