"use client";
import{useEffect,useMemo,useState}from"react";import{Bell,Search,RefreshCw,ExternalLink,TrendingUp,Newspaper,Radio}from"lucide-react";
type A={id:string;title:string;summary:string;source:string;articleUrl:string;category:string;publishedAt:string};
const cats=["All","Politics","Business","Sports","Technology","Crime","Health","Education","Weather","Entertainment","Science","World"];
export default function Home(){const[a,setA]=useState<A[]>([]),[s,setS]=useState<any>({}),[cat,setCat]=useState("All"),[q,setQ]=useState(""),[busy,setBusy]=useState(false);
async function load(){const j=await(await fetch("/api/articles",{cache:"no-store"})).json();setA(j.articles);setS(j.stats)}async function refresh(){setBusy(true);try{await fetch("/api/ingest",{method:"POST"});await load()}finally{setBusy(false)}}useEffect(()=>{load()},[]);
const f=useMemo(()=>a.filter(x=>(cat==="All"||x.category===cat)&&(!q||x.title.toLowerCase().includes(q.toLowerCase())||x.summary.toLowerCase().includes(q.toLowerCase()))),[a,cat,q]);return <main>
<nav><div className="brand">🇱🇰 <b>LankaNews</b> <i>AI</i></div><div className="links"><a href="#latest">Latest</a><a href="#brief">Daily Brief</a></div><button className="icon"><Bell size={17}/></button></nav>
<section className="hero"><div><label>● LIVE SRI LANKA NEWS INTELLIGENCE</label><h1>Know what’s happening.<br/><span>Not just what was published.</span></h1><p>One clean feed from Sri Lankan publishers, organized by topic and ready to explore.</p><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search stories, topics or keywords..."/></div></div><aside><small>LIVE MONITOR</small><strong>{s.total||0}</strong><span>stories in the feed</span><button onClick={refresh} disabled={busy}><RefreshCw size={15}/> {busy?"Collecting…":"Collect latest"}</button></aside></section>
<section className="stats"><div><Newspaper/><b>{s.total||0}</b><small>Stories tracked</small></div><div><Radio/><b>{s.sources||0}</b><small>Publishers</small></div><div><TrendingUp/><b>{s.recent||0}</b><small>Recent stories</small></div><div><span className="green"></span><b>15m</b><small>Collection cycle</small></div></section>
<section className="content" id="latest"><div className="head"><div><label>DISCOVER</label><h2>Latest intelligence</h2></div></div><div className="chips">{cats.map(c=><button className={cat===c?"active":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="grid">{f.map(x=><article className="card" key={x.id}><div className="meta"><b>{x.category}</b><span>{x.source}</span></div><h3>{x.title}</h3><p>{x.summary}</p><footer><span>{new Date(x.publishedAt).toLocaleString("en-LK")}</span><a href={x.articleUrl} target="_blank" rel="noreferrer">Original <ExternalLink size={13}/></a></footer></article>)}</div></section>
<section className="brief" id="brief"><div><label>ROADMAP</label><h2>Daily Brief</h2><p>Next: AI story clustering, multilingual summaries, semantic search and trending-topic analysis.</p></div><div className="road"><div>01 <b>Cluster stories</b><span>Connect coverage of the same event.</span></div><div>02 <b>Summarize facts</b><span>Short summaries with original links.</span></div><div>03 <b>Surface trends</b><span>Measure topic velocity across publishers.</span></div></div></section><footer><b>LankaNews AI</b><span>Original publishers remain the source of record.</span></footer></main>